// Code generated by xgen. DO NOT EDIT.
package xgen

import (
	"github.com/nduyhai/xcore/error/gerr"
	"google.golang.org/grpc/codes"
)

var (
	// CoreUserIDNotFound represents User not found
	CoreUserIDNotFound = gerr.NewGRPCReason("CORE_1", "User not found", codes.NotFound)
	// CoreInvalidInput represents Invalid input provided
	CoreInvalidInput = gerr.NewGRPCReason("CORE_2", "Invalid input provided", codes.InvalidArgument)
	// CoreInternalError represents Internal server error
	CoreInternalError = gerr.NewGRPCReason("CORE_3", "Internal server error", codes.Internal)
)
