// Code generated by xgen. DO NOT EDIT.
package xgen

import (
	"github.com/nduyhai/xcore/error/xerr"
	"github.com/nduyhai/xcore/error/gerr"
	"google.golang.org/grpc/codes"
)

var (
	// PaymentUserIDNotFound represents User not found
	PaymentUserIDNotFound = xerr.NewHTTPReason("PAYMENT_1", "User not found", 404)
	// PaymentInvalidInput represents Invalid input provided
	PaymentInvalidInput = gerr.NewGRPCReason("PAYMENT_2", "Invalid input provided", codes.InvalidArgument)
	// PaymentInternalError represents Internal server error
	PaymentInternalError = gerr.NewMultiReason("PAYMENT_3", "Internal server error", 500, codes.Internal)
)
