// Code generated by xgen. DO NOT EDIT.
package xgen

import (
	"github.com/nduyhai/xcore/error/xerr"
)

var (
	// UserUserIDNotFound represents User not found
	UserUserIDNotFound = xerr.NewHTTPReason("USER_1", "User not found", 404)
	// UserInvalidInput represents Invalid input provided
	UserInvalidInput = xerr.NewHTTPReason("USER_2", "Invalid input provided", 401)
	// UserInternalError represents Internal server error
	UserInternalError = xerr.NewHTTPReason("USER_3", "Internal server error", 500)
)
