// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: reason.proto

package gerr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtoReason represents a reason that can be transmitted via GRPC error details
type ProtoReason struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error_code is the string representation of the error code
	ErrorCode string `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// error_message is the human-readable error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// http_code is the optional HTTP status code
	HttpCode *int32 `protobuf:"varint,3,opt,name=http_code,json=httpCode,proto3,oneof" json:"http_code,omitempty"`
	// grpc_code is the optional GRPC status code
	GrpcCode      *int32 `protobuf:"varint,4,opt,name=grpc_code,json=grpcCode,proto3,oneof" json:"grpc_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoReason) Reset() {
	*x = ProtoReason{}
	mi := &file_reason_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoReason) ProtoMessage() {}

func (x *ProtoReason) ProtoReflect() protoreflect.Message {
	mi := &file_reason_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoReason.ProtoReflect.Descriptor instead.
func (*ProtoReason) Descriptor() ([]byte, []int) {
	return file_reason_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoReason) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ProtoReason) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProtoReason) GetHttpCode() int32 {
	if x != nil && x.HttpCode != nil {
		return *x.HttpCode
	}
	return 0
}

func (x *ProtoReason) GetGrpcCode() int32 {
	if x != nil && x.GrpcCode != nil {
		return *x.GrpcCode
	}
	return 0
}

var File_reason_proto protoreflect.FileDescriptor

const file_reason_proto_rawDesc = "" +
	"\n" +
	"\freason.proto\x12\x04gerr\"\xb1\x01\n" +
	"\vProtoReason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12 \n" +
	"\thttp_code\x18\x03 \x01(\x05H\x00R\bhttpCode\x88\x01\x01\x12 \n" +
	"\tgrpc_code\x18\x04 \x01(\x05H\x01R\bgrpcCode\x88\x01\x01B\f\n" +
	"\n" +
	"_http_codeB\f\n" +
	"\n" +
	"_grpc_codeBl\n" +
	"\bcom.gerrB\vReasonProtoP\x01Z#github.com/nduyhai/xcore/error/gerr\xa2\x02\x03GXX\xaa\x02\x04Gerr\xca\x02\x04Gerr\xe2\x02\x10Gerr\\GPBMetadata\xea\x02\x04Gerrb\x06proto3"

var (
	file_reason_proto_rawDescOnce sync.Once
	file_reason_proto_rawDescData []byte
)

func file_reason_proto_rawDescGZIP() []byte {
	file_reason_proto_rawDescOnce.Do(func() {
		file_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reason_proto_rawDesc), len(file_reason_proto_rawDesc)))
	})
	return file_reason_proto_rawDescData
}

var file_reason_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reason_proto_goTypes = []any{
	(*ProtoReason)(nil), // 0: gerr.ProtoReason
}
var file_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reason_proto_init() }
func file_reason_proto_init() {
	if File_reason_proto != nil {
		return
	}
	file_reason_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reason_proto_rawDesc), len(file_reason_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reason_proto_goTypes,
		DependencyIndexes: file_reason_proto_depIdxs,
		MessageInfos:      file_reason_proto_msgTypes,
	}.Build()
	File_reason_proto = out.File
	file_reason_proto_goTypes = nil
	file_reason_proto_depIdxs = nil
}
